### ISSUE TITLE
"Invoke ML pipeline" is canceled

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/MLOpsPython#129]
During the job: "Run_ML_Pipeline", the 'Invoke ML pipeline' step is canceled without any error.
[MlOps-Error.docx](https://github.com/microsoft/MLOpsPython/files/3967984/MlOps-Error.docx)

**Comment by eedorenko** [comment]
Note: If the model evaluation determines that the new model does not perform better than the previous one then the new model will not be registered and the pipeline will be cancelled.

**Comment by zepef** [comment]
Hello,
I run into an "Invoke ML pipeline" error at Train model/Trigger ML pipeline
at the end of "Determine if evaluation succeeded and new model is registered" I get

/usr/local/envs/mlopspython_ci/bin/az account set --subscription 24d53115-08eb-4b84-8c18-c2e5c4207517
/bin/bash /__w/_temp/azureclitaskscript1588226437106.sh
Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
No Model found with name: diabetes_regression_model.pkl. tag_name: BuildId, tag_value: 6.
Model was not registered for this run.
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1

Do you have any idea of what is going wrong ?

Thanks a lot

**Comment by al5848** [comment]
Hi @zepef 

Did you ever manage to resolve your issue? I'm currently running into the same problem.

Thank you
Allen

> Hello,
> I run into an "Invoke ML pipeline" error at Train model/Trigger ML pipeline
> at the end of "Determine if evaluation succeeded and new model is registered" I get
> 
> /usr/local/envs/mlopspython_ci/bin/az account set --subscription 24d53115-08eb-4b84-8c18-c2e5c4207517
> /bin/bash /__w/_temp/azureclitaskscript1588226437106.sh
> Warning: Falling back to use azure cli login credentials.
> If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
> Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
> No Model found with name: diabetes_regression_model.pkl. tag_name: BuildId, tag_value: 6.
> Model was not registered for this run.
> ##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1
> 
> Do you have any idea of what is going wrong ?
> 
> Thanks a lot

**Comment by zepef** [comment]
Allen,

I haven't rethought the subject, but I'll do it this week. I'll let you know because this mlops solution seems interesting to me.

Bien cordialement,

Pierre-Emmanuel FEGA

De : Allen Aze <notifications@github.com>
Envoyé : vendredi 3 juillet 2020 17:14
À : microsoft/MLOpsPython <MLOpsPython@noreply.github.com>
Cc : Pierre-Emmanuel FEGA <zepef@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/MLOpsPython] "Invoke ML pipeline" is canceled (#129)


Hi @zepef<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzepef&data=02%7C01%7C%7Cf9113c53a97b49ddaea808d81f5b6052%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637293824596070206&sdata=Msqd1FaowgJKoHyGsoDe8XU2kD5bJTlrVTNt4XinDDs%3D&reserved=0>

Did you ever manage to resolve your issue? I'm currently running into the same problem.

Thank you
Allen

Hello,
I run into an "Invoke ML pipeline" error at Train model/Trigger ML pipeline
at the end of "Determine if evaluation succeeded and new model is registered" I get

/usr/local/envs/mlopspython_ci/bin/az account set --subscription 24d53115-08eb-4b84-8c18-c2e5c4207517
/bin/bash /__w/_temp/azureclitaskscript1588226437106.sh
Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
No Model found with name: diabetes_regression_model.pkl. tag_name: BuildId, tag_value: 6.
Model was not registered for this run.
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1

Do you have any idea of what is going wrong ?

Thanks a lot

**Comment by zepef** [comment]
Hi Allen,

I just installed a new Windows version with WSL2. I will let You know if I am still encountering the same issue.

Best regards,

Pierre-Emmanuel

De : Allen Aze <notifications@github.com>
Envoyé : vendredi 3 juillet 2020 17:14
À : microsoft/MLOpsPython <MLOpsPython@noreply.github.com>
Cc : Pierre-Emmanuel FEGA <zepef@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/MLOpsPython] "Invoke ML pipeline" is canceled (#129)


Hi @zepef<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzepef&data=02%7C01%7C%7Cf9113c53a97b49ddaea808d81f5b6052%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637293824596070206&sdata=Msqd1FaowgJKoHyGsoDe8XU2kD5bJTlrVTNt4XinDDs%3D&reserved=0>

Did you ever manage to resolve your issue? I'm currently running into the same problem.

Thank you
Allen

Hello,
I run into an "Invoke ML pipeline" error at Train model/Trigger ML pipeline
at the end of "Determine if evaluation succeeded and new model is registered" I get

/usr/local/envs/mlopspython_ci/bin/az account set --subscription 24d53115-08eb-4b84-8c18-c2e5c4207517
/bin/bash /__w/_temp/azureclitaskscript1588226437106.sh
Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
No Model found with name: diabetes_regression_model.pkl. tag_name: BuildId, tag_value: 6.
Model was not registered for this run.
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1

Do you have any idea of what is going wrong ?

Thanks a lot

**Comment by zepef** [comment]
Hello Allen,

I did not retry to have this particular example working. Instead I ran into an excellent tutorial which I fully succeeded to reproduce.
I advise You to try: https://benalexkeen.com/creating-end-to-end-mlops-pipelines-using-azure-ml-and-azure-pipelines-part-1/
I am using it now for my own professional purposes and I think it is an excellent foundation for more complex CI/CD MLOps work.

All the best,

Pierre-Emmanuel


De : Allen Aze <notifications@github.com>
Envoyé : vendredi 3 juillet 2020 17:14
À : microsoft/MLOpsPython <MLOpsPython@noreply.github.com>
Cc : Pierre-Emmanuel FEGA <zepef@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/MLOpsPython] "Invoke ML pipeline" is canceled (#129)


Hi @zepef<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzepef&data=02%7C01%7C%7Cf9113c53a97b49ddaea808d81f5b6052%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637293824596070206&sdata=Msqd1FaowgJKoHyGsoDe8XU2kD5bJTlrVTNt4XinDDs%3D&reserved=0>

Did you ever manage to resolve your issue? I'm currently running into the same problem.

Thank you
Allen

Hello,
I run into an "Invoke ML pipeline" error at Train model/Trigger ML pipeline
at the end of "Determine if evaluation succeeded and new model is registered" I get

/usr/local/envs/mlopspython_ci/bin/az account set --subscription 24d53115-08eb-4b84-8c18-c2e5c4207517
/bin/bash /__w/_temp/azureclitaskscript1588226437106.sh
Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
No Model found with name: diabetes_regression_model.pkl. tag_name: BuildId, tag_value: 6.
Model was not registered for this run.
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1

Do you have any idea of what is going wrong ?

Thanks a lot

**Comment by oumaramzadia** [comment]
Anybody has an idea why this error is happening and how to fix it please?
