### ISSUE TITLE
Enhance folder structure

### ISSUE THREAD

**Issue by xinyi-joffre** [microsoft/MLOpsPython#137]
It would be great to improve the existing docs/code.md file by actually showing the full folder structure along with the explanations. Also, the pipelines heading should maybe more specifically call out "AzDO Pipelines"

Along with that change, below are some other considerations for the folders structure of this repo.

Proposed changes:

1. Have an example of how to manage model configuration and what are the best practices for managing it in production. For instance, for some teams, it can help to check in the model_config.json to the repo if there are many parameters. This means it can be peer reviewed.
1. Have a place to hold notebooks or other prototype files (consider "playground", "experimentation", or "notebooks" folder)
1.  If possible, it would be good to reduce the number of sys.path imports, since regular imports have more intellisense and get by the linter easier
1. Test location is debatable, but having tests close to the individual scripts may be easier to maintain for larger repos
1. Consider renaming "code" to the project name, since "code" is a python built-in module and causes interesting behavior with vscode test discovery
1. Consider how to handle multiple models that may share common code. We could consider calling out how to do it in the "Bring your own model" docs.
1. It make sense to add a .amlignore file in the repo to ignore /tests and other non-required files

**Comment by sbaidachni** [comment]
To reduce sys.path "imports" we will need to make some additional actions:
1). add __init__.py to all related folders;
2). Use module notation in imports like ml_service.utils.attach_cluster
3). call scripts using module notation python -m ml_service.pipelines.run_train_pipeline.py in yaml files
Of course, it will affect users who are running everything locally (offlineRun). So, I am not sure if it's really valuable due to increasing complexity of the code. What do you think?

**Comment by dtzar** [comment]
Related #184
