### ISSUE TITLE
Error in 'Invoke ML pipeline'

### ISSUE THREAD

**Issue by FMauroy** [microsoft/MLOpsPython#153]
Hi, don't know if I'm doing something wrong, but I followed the tutorial to the letter but have the following error during the "Train model Trigger ML Training Pipeline' step in Azure DevOps:

`URL https://.aether.ms/api/v1.0/subscriptions/_GUID_/resourceGroups//providers/Microsoft.MachineLearningServices/workspaces//PipelineRuns/PipelineSubmit/_GUID_ for HttpRequest is not correct.`

The domain name misses a part, and the resource group name and workspace are not filled. I redacted the GUIDs.

In the new workspace at https://ml.azure.com/pipelines, I do not see anything, but in the old (in the Azure Portal), I see a list of pipelines, with a proper URL:
`https://westeurope.aether.ms/api/v1.0/subscriptions/_GUID_/resourceGroups/MLOps-Tests/providers/Microsoft.MachineLearningServices/workspaces/mlops-AML-WS/PipelineRuns/PipelineSubmit/_GUID_`

Is West Europe maybe not a supported value for this preview? Or am I missing something obvious?

Thanks a lot for any help.
Regards

**Comment by sbaidachni** [comment]
Yeah. This happens if your service connection (under WORKSPACE_SVC_CONNECTION name in devopsforai-aml-vg variable group) has wrong scope. It should be in Machine Learning scope rather than in Subscription scope. So, just recreated service connection using the right scope pointing it to your workspace. Please, confirm that it works.

**Comment by FMauroy** [comment]
Thanks a lot for the reply. I just tried and it worked! Sorry about that, my bad.
