### ISSUE TITLE
missing arguments in the api call to run the ml pipeline

### ISSUE THREAD

**Issue by MichielMosmans** [microsoft/MLOpsPython#195]
The job: "Run_ML_Pipeline" results in an invalid http request:

URL https://[missing region].aether.ms/api/v1.0/subscriptions/xxx/resourceGroups/[missing rg]/providers/Microsoft.MachineLearningServices/workspaces/[missing workspace]/PipelineRuns/PipelineSubmit/xxx for HttpRequest is not correct.

These values are available in a variable group in devops and this group is included in the ci-build-train.yml. Any suggestions on why this is happening and how it should be resolved?

**Comment by dtzar** [comment]
This is because you haven't set the proper scope (must be AML Workspace) for your Azure Resource Group service connection.  Please follow the steps as called out in the getting started guide.

**Comment by JyotiRSharma** [comment]
My understanding is, if I have a Service Connection of Subscription level(as it is a super set of resouces inside it) it should be able to do modifications over resources like Azure ML Workspace.

I have set the WORKSPACE_SVC_CONNECTION to the Subscription Level service connection, but I get this error in the "Run_ML_Pipeline" job.

So that being said, it is still necessary to go back and create a Machine Learning Workspace scope?
