### ISSUE TITLE
Deployment Failed for Enterprise ML 

### ISSUE THREAD

**Issue by craigjurs** [microsoft/MLOpsPython#271]
This is probably a dumb one, but I've reached the end of my understanding to solve the issue. When I run the pipeline the deployment fails because my ML resource is "enterprise"

```
Template deployment validation was completed successfully.
Starting Deployment.
Deployment name is cloud-environment-20200428-210003-a450
There were errors in your deployment. Error code: DeploymentFailed.
##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
##[error]Details:
**##[error]Invalid: Downgrade from Enterprise sku to Basic sku is not allowed**
##[error]Task failed while creating or updating the template deployment.
Finishing: Deploy MLOps resources to Azure
```

So I went into the template file and added the following code after "location":

```
    "sku":{
      "type": "string",
      "defaultValue": "enterprise",
        "allowedValues": [
          "basic",
          "enterprise"
      ],
      "metadata": {
         "description": "Specifies the sku, also referred as 'edition' of the Azure Machine Learning workspace."
      }
    },
```

Unfortunately I still get the exact same error message.

**Comment by craigjurs** [comment]
Just for clarification, if I use a "basic" ML workspace, and not an "enterprise" one, then everything goes as expected

**Comment by j-so** [comment]
To confirm, you added the code [after "location", in the "parameters" section](https://github.com/microsoft/MLOpsPython/blob/32dd48fef2fc77439e2fe1947282a7192a0bfd9f/environment_setup/arm-templates/cloud-environment.json#L13)? 

If you haven't done so already, you'll also need to add this code [after "location" in the workspace definition](https://github.com/microsoft/MLOpsPython/blob/32dd48fef2fc77439e2fe1947282a7192a0bfd9f/environment_setup/arm-templates/cloud-environment.json#L124) in order to pass the sku tier to the workspace definition.
```
"sku": {
  "tier": "[parameters('sku')]",
  "name": "[parameters('sku')]"
},
```

**Comment by craigjurs** [comment]
@j-so works now, thank you for the help. I did not have the second step you provided.
