### ISSUE TITLE
Pipeline Resource model-train-ci Input Must be Valid error while trying to excute the set-up-the-release-deployment steps

### ISSUE THREAD

**Issue by rituraj17** [microsoft/MLOpsPython#353]
Hi All,
I am facing issues while following the steps to Set up the Release Deployment and/or Batch Scoring pipelines
Can anyone help me to understand how why it so?
I am not able to understand where to make this part  **If you plan to use the release deployment pipeline (in the next section), you will need to rename this pipeline to Model-Train-Register-CI.**

.pipelines/diabetes_regression-cd.yml (Line: 19, Col: 15): Pipeline Resource model-train-ci Input Must be Valid.

Reference :
- https://github.com/microsoft/MLOpsPython/blob/master/docs/getting_started.md#set-up-the-model-ci-training-evaluation-and-registration-pipeline
- https://github.com/microsoft/MLOpsPython/blob/master/docs/getting_started.md#set-up-the-release-deployment-andor-batch-scoring-pipelines

**Comment by rituraj17** [comment]
Also, want to know what is a pipeline name and how to change it in the diabetes_regression-ci.yml  file?

**Comment by j-so** [comment]
Pipeline names are not set in the yml file. To change the name, click the menu at the top right corner of the pipeline screen:
![image](https://user-images.githubusercontent.com/5027592/110841153-68b08b00-825a-11eb-84bb-3bef6e735726.png)

In order to for the Release Deployment and Batch Scoring pipeline to use the artifacts created by the training pipeline, the training pipeline has to be named properly.

**Comment by j-so** [comment]
Closing this issue - please reopen if needed.
