### ISSUE TITLE
Include connection to training/scoring data sources

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#75]
The template should include realistic guidance on how to connect to data sources:
- For training, how to connect to data sources (whether of a type supported by Azure ML Datasource classes, or other ODBC data source type)
- Whether we should have a separate pipeline stage for pulling the data (separation of concerns + reuse of run steps) or just query the data in the training step
- How to manage credentials, one way is to use Key Vault in the run script itself (https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb) but it's hard to find, should be part of the solution template (+any other method to manage credentials if appropriate)
- For *scoring*, similarly how to manage connectivity to data sources. Enterprise DS models often enrich incoming requests with data from a data mart (e.g. user profiles)

**Comment by sebader** [comment]
+1 there should be at least one sample that uses the Azure ML managed data stores.
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-access-data#train

**Comment by dtzar** [comment]
I believe this is fixed by #134. I'd like to keep the DataOps for ML cycle separate from this repo - and yes it should be in its own pipeline.  Eugene is working on other supporting documents in this space. 
 Key Vault integration is present with Azure DevOps task groups.  We link to existing documentation on how to add different types of data sets which will work with this approach.
